export default function DiningPage(){
    return(
        <div>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
            <p>Dining</p>
        </div>
    );
}