export default function EventsPage(){
    return(
        <div>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
            <p>Events</p>
        </div>
    );
}